model:
  model_name_or_path: "zhihan1996/DNABERT-2-117M"
  use_fp16: false
  use_8bit: false
  use_4bit: false
method:
  finetuning_type: "lora"
  lora_r: 8
  lora_alpha: 32
  lora_dropout: 0.05
  lora_target: "all"

dataset:
  data_path: /mnt/c/Users/11817/GenomeAI/My_GenomeAI/species_classification
  kmer: -1

train:
  classification: false
  regression: true
  run_name: "lora_sft_run"
  model_max_length: 128
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 1
  learning_rate: 3.0e-5
  num_train_epochs: 10
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1
  fp16: false
  ddp_timeout: 180000000
  logging_steps: 50
  save_steps: 50
  evaluation_strategy: "steps"
  eval_steps: 50
  warmup_steps: 50
  save_total_limit: 3
  load_best_model_at_end: true
  use_wandb: false
  saved_model_dir: "./lora_Trained_model666"
output:
  output_dir: "output_sft_lora"
  plot_loss: false
  overwrite_output_dir: true
