torchrun --nproc_per_node=1 --node_rank=0 --master_addr="localhost" --master_port=12355 --nnodes=1  training.py \
    --config_name ./model/model_gpt2 \
    --tokenizer_name zhihan1996/DNABERT-2-117M \
    --train_file train.txt \
    --validation_file dev.txt \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy steps \
    --logging_steps 100 \
    --save_steps 2000 \
    --eval_steps 2000 \
    --warmup_ratio 0.05 \
    --learning_rate 4e-4 \
    --save_total_limit 10 \
    --block_size 128 \
    --do_train \
    --do_eval \
    --bf16 \
    --overwrite_output_dir \
    --preprocessing_num_workers 16 \
    --output_dir ./tmp/test-mixtral --remove_unused_columns=False