setup:
  data_file: "sequences_sae.txt"
  d_model: 768
  d_hidden: 4096
  batch_size: 48
  lr: 2e-4
  k: 64
  auxk: 256
  dead_steps_threshold: 2000
  max_epochs: 3
  num_devices: 1
  model_suffix: ""
  wandb_project: "pGenomeOcean"
  num_workers: None
  model_name: "pGenomeOcean/GenomeOcean-4B"
