model:
  model_name_or_path:  "pGenomeOcean/GenomeOcean-100M" 


method:
  finetuning_type: "full"

dataset:
  data_path: ["/projects/p32572/All_benchmark/H3", "./species_classification_1"]

train:
  use_flash_attention: false
  classification: true
  regression: false
  run_name: ["full_sft_run_0", "full_sft_run_1"]
  model_max_length: [128, 128]
  per_device_train_batch_size: [8, 8]
  per_device_eval_batch_size: [16, 16]
  gradient_accumulation_steps: [1, 1]
  learning_rate: [3.0e-5, 3.0e-5]
  num_train_epochs: [3, 3]
  lr_scheduler_type: ["cosine", "cosine"]
  warmup_ratio: [0.1, 0.1]
  fp16: false
  bf16: false
  ddp_timeout: 180000000
  logging_steps: [50, 50]
  save_steps: [50, 50]
  evaluation_strategy: ["steps", "steps"]
  eval_steps: [50, 50]
  warmup_steps: [50, 50]
  save_total_limit: [3, 3]
  load_best_model_at_end: true
  use_wandb: false
  saved_model_dir: ["./Trained_model_0", "./Trained_model_1"]
output:
  output_dir: ["output_sft_full_0", "output_sft_full_1"]
  overwrite_output_dir: true
