setup:
  model_name_or_path: evo-1-131k-base
  data_path: ["/projects/p32572/All_benchmark/H3","/projects/p32572/All_benchmark/H3K4me1"]
  kmer: [-1,-1]
  run_name: ["EVO_H3_seed28","EVO_H3K4me1_seed28"]
  model_max_length: [1000,1000]
  per_device_train_batch_size: [16,16]
  per_device_eval_batch_size: [16,16]
  gradient_accumulation_steps: [2,2]
  learning_rate: [3e-4,3e-4]
  num_train_epochs: [3,3]
  save_steps: [200,200] 
  output_dir: ["output_seed/EVO","output_seed/EVO"]
  evaluation_strategy: "steps"
  eval_steps: [200,200]
  warmup_steps: [50,50]
  logging_steps: [100000,100000]
  overwrite_output_dir: True
  log_level: "info"
  find_unused_parameters: False
  use_lora: True
  lora_r: [8,8]
  lora_alpha: [32,32]
  lora_dropout: [0.05,0.05]
  lora_target_modules: "Wqkv,projections"
  cache_dir: "/projects/p32572"
  lr_scheduler_type: "linear"
  warmup_ratio: 0.1
  dataloader_drop_last: True
  metric_for_best_model: "matthews_correlation"
  weight_decay: 0.01
  load_best_model_at_end: True

